apps/api/urls.py
from django.urls import path
from . import views

app_name = "api"
urlpatterns = [
    path("system_status/", views.SystemStatusView.as_view(), name="system_status"),
    path("user/settings/", views.UserSettingsView.as_view(), name="user_settings"),
    path("subscribe/", views.SubscribeView.as_view(), name="subscribe"),
    path("reset_ss_port/", views.ReSetSSPortView.as_view(), name="reset_ss_port"),
    path("gen/invitecode/", views.gen_invite_code, name="geninvitecode"),
    path("shop/", views.purchase, name="purchase"),
    path("change/theme/", views.change_theme, name="change_theme"),
    path("change/sub_type/", views.change_sub_type, name="change_sub_type"),
    path("checkin/", views.UserCheckInView.as_view(), name="checkin"),
    # web api 接口
    path(
        "user_ss_config/<int:node_id>/",
        views.UserSSConfigView.as_view(),
        name="user_ss_config",
    ),
    path(
        "user_vmess_config/<int:node_id>/",
        views.UserVmessConfigView.as_view(),
        name="user_vmess_config",
    ),
    path(
        "vmess_server_config/<int:node_id>/",
        views.VmessServerConfigView.as_view(),
        name="vmess_server_config",
    ),
    # 支付
    path("orders", views.OrderView.as_view(), name="order"),
    path("callback/alipay", views.ailpay_callback, name="alipay_callback"),
    # user stats
    path(
        "user/stats/ref_chart", views.UserRefChartView.as_view(), name="user_ref_chart"
    ),
    path(
        "user/stats/traffic_chart",
        views.UserTrafficChartView.as_view(),
        name="user_traffic_chart",
    ),
]

apps/sspanel/urls.py
from django.urls import path
from apps.sspanel import views, admin_views


app_name = "sspanel"
urlpatterns = [
    # 网站用户面板
    path("sshelp/", views.sshelp, name="sshelp"),
    path("ssclient/", views.ssclient, name="ssclient"),
    path("invitecode/", views.InviteCodeView.as_view(), name="invite_code"),
    # 注册/登录
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.user_login, name="login"),
    path("logout/", views.user_logout, name="logout"),
    # 节点
    path("nodeinfo/", views.NodeInfoView.as_view(), name="nodeinfo"),
    path("user_traffic_log/", views.UserTrafficLog.as_view(), name="user_traffic_log"),
    # 用户信息
    path("users/userinfo/", views.UserInfoView.as_view(), name="userinfo"),
    path(
        "users/ss_node_config/",
        views.UserSSNodeConfigView.as_view(),
        name="ss_node_config",
    ),
    # 捐赠/充值
    path("donate/", views.donate, name="donate"),
    path("shop/", views.ShopView.as_view(), name="shop"),
    path("purchaselog/", views.purchaselog, name="purchaselog"),
    path("chargecenter/", views.chargecenter, name="chargecenter"),
    path("charge/", views.charge, name="charge"),
    # 公告
    path("announcement/", views.announcement, name="announcement"),
    # 工单
    path("ticket/", views.ticket, name="ticket"),
    path("ticket/create/", views.ticket_create, name="ticket_create"),
    path("ticket/edit/(<int:pk>)/", views.ticket_edit, name="ticket_edit"),
    path("ticket/delete/<int:pk>)/", views.ticket_delete, name="ticket_delete"),
    # 推广相关
    path("aff/invite/", views.AffInviteView.as_view(), name="aff_invite"),
    path("aff/status/", views.AffStatusView.as_view(), name="aff_status"),
    # ====================================================================
    # 网站后台界面
    # ====================================================================
    path(
        "backend/user_online_ip_log/",
        admin_views.UserOnlineIpLogView.as_view(),
        name="user_online_ip_log",
    ),
    path("backend/", admin_views.system_status, name="system_status"),
    # 邀请码相关
    path("backend/invite/", admin_views.backend_invite, name="backend_invite"),
    path("invite_gen_code/", admin_views.gen_invite_code, name="geninvitecode"),
    # 节点相关
    path(
        "backend/node_list/",
        admin_views.NodeListView.as_view(),
        name="backend_node_list",
    ),
    path(
        "backend/node/<str:node_type>/",
        admin_views.NodeView.as_view(),
        name="backend_node",
    ),
    path(
        "backend/node_delete/<str:node_type>/<int:node_id>/",
        admin_views.NodeDeleteView.as_view(),
        name="backend_node_delete",
    ),
    path(
        "backend/ss_node/<str:node_type>/<int:node_id>/",
        admin_views.NodeDetailView.as_view(),
        name="backend_node_detail",
    ),
    # 用户相关
    path(
        "backend/user_ss_config_list/",
        admin_views.UserSSConfigListView.as_view(),
        name="backend_user_ss_config_list",
    ),
    path(
        "backend/user_ss_config/delete/<int:pk>/",
        admin_views.UserSSConfigDeleteView.as_view(),
        name="backend_user_ss_config_delete",
    ),
    path(
        "backend/user_ss_config/search/",
        admin_views.UserSSConfigSearchView.as_view(),
        name="backend_user_ss_config_search",
    ),
    path(
        "backend/user_ss_config/<int:user_id>/",
        admin_views.UserSSConfigDetailView.as_view(),
        name="backend_user_ss_config_detail",
    ),
    path(
        "backend/user_status/",
        admin_views.UserStatusView.as_view(),
        name="backend_user_status",
    ),
    # 商品充值相关
    path("backend/charge/", admin_views.backend_charge, name="backend_charge"),
    path("backend/shop/", admin_views.backend_shop, name="backend_shop"),
    path("backend/shop/delete/<int:pk>/", admin_views.good_delete, name="good_delete"),
    path("backend/good/create/", admin_views.good_create, name="good_create"),
    path("backend/good/edit/<int:pk>/", admin_views.good_edit, name="good_edit"),
    path(
        "backend/purchase/history/",
        admin_views.purchase_history,
        name="purchase_history",
    ),
    # 公告管理相关
    path("backend/anno/", admin_views.backend_anno, name="backend_anno"),
    path("backend/anno/delete/<int:pk>/", admin_views.anno_delete, name="anno_delete"),
    path("backend/anno/create/", admin_views.anno_create, name="anno_create"),
    path("backend/anno/edit/<int:pk>/", admin_views.anno_edit, name="anno_edit"),
    # 工单相关
    path("backend/ticket/", admin_views.backend_ticket, name="backend_ticket"),
    path(
        "backend/ticket/edit/<int:pk>/",
        admin_views.backend_ticketedit,
        name="backend_ticketedit",
    ),
]

apps/urls.py
from django.urls import path, include
from django.contrib import admin

from apps.sspanel.views import index

urlpatterns = [
    path("", index, name="index"),
    path("admin/", admin.site.urls, name="admin"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("jet/", include("jet.urls", "jet")),
    path("prom/", include("django_prometheus.urls")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("sspanel/", include("apps.sspanel.urls", namespace="sspanel")),
]

templates/backendbase.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load staticfiles %}
    <title>{% settings_value "TITLE" %}</title>
    {% include "basehead.html" %}
</head>

<body>
    <nav class="navbar is-primary is-spaced">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'index' %}">首页</a>
                <a class="navbar-item" href="{% url 'sspanel:sshelp' %}">使用说明</a>
                <a class="navbar-item" href="{% url 'sspanel:invite_code' %}">邀请码</a>
                <a class="navbar-item" href="{% url 'sspanel:ssclient' %}">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-primary is-inverted" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'sspanel:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active">面板管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:system_status' %}">系统状态</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_invite' %}">邀请相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_anno' %}">公告管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_ticket' %}">工单管理</a>
                    <a class="navbar-item is-active">节点管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_node_list' %}">节点列表</a>
                    <a class="navbar-item" href="{% url 'sspanel:user_online_ip_log' %}">在线IP</a>
                    <a class="navbar-item is-active">交易管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_charge' %}">充值管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_shop' %}">商品管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:purchase_history' %}">购买记录</a>
                    <a class="navbar-item is-active">用户管理</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_user_ss_config_list' %}">用户列表</a>
                    <a class="navbar-item" href="{% url 'sspanel:backend_user_status' %}">用户分析</a>
                    <a class="navbar-item is-active">面板跳转</a>
                    <a class="navbar-item" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">用户面板</a>
                </div>
            </div>
        </div>
    </nav>
    <section class="hero is-small is-primary">
        <!-- Hero content: will be in the middle -->
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    <a href="/">
                        <strong>{% settings_value "SUBTITLE" %}</strong>
                    </a>
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <br />
    <div class="container is-fluid">
        <div class="columns">
            <div class="column is-2 is-hidden-mobile">
                <div class="box">
                    {% if user.is_authenticated %}
                    <aside class="menu">
                        <p class="menu-label">
                            面板管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:system_status' %}">系统状态</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_invite' %}">邀请相关</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_anno' %}">公告管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_ticket' %}">工单管理</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            节点管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:backend_node_list' %}">节点列表</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:user_online_ip_log' %}">在线IP</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            交易管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:backend_charge' %}">充值管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_shop' %}">商品管理</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:purchase_history' %}">购买记录</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            用户管理
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:backend_user_ss_config_list' %}">用户列表</a>
                            </li>
                            <li>
                                <a href="{% url 'sspanel:backend_user_status' %}">用户分析</a>
                            </li>
                        </ul>
                        <p class="menu-label">
                            面板跳转
                        </p>
                        <ul class="menu-list">
                            <li>
                                <a href="/admin">数据后台</a>
                            </li>
                        </ul>
                        <ul class="menu-list">
                            <li>
                                <a href="{% url 'sspanel:userinfo' %}">用户面板</a>
                            </li>
                        </ul>
                        {% endif %}
                    </aside>
                </div>
            </div>
            <div class="column is-10">
                {% block main %} {% endblock main%}
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2018·
                        <a href="https://github.com/ehco1996">GitHub</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 -->
{% if messages %}
<script>
    {% for message in messages %}
    swal("{{ message.extra_tags }}", '{{ message }}', '{{ message.level_tag }}');
    {% endfor %}
</script>
{% endif %}

</html>

templates/base.html
{% load ehcofilter %}
<!DOCTYPE html>
<html lang="zh">

<head>
    {% load staticfiles %}
    <title>{% settings_value "TITLE" %}</title>
    {% include "basehead.html" %}
</head>

<body>
    <nav class="navbar is-info is-spaced">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'index' %}">
                <img src="{% static 'img/logo/logo.png' %}" alt="谜之屋logo" width="112" height="28">
            </a>
            <div class="navbar-burger burger" data-target="navMenuColorprimary-example">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="navMenuColorprimary-example" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="{% url 'index' %}">首页</a>
                <a class="navbar-item" href="{% url 'sspanel:sshelp' %}">使用说明</a>
                <a class="navbar-item" href="{% url 'sspanel:invite_code' %}">邀请码</a>
                {% if user.is_authenticated %}
                <a class="navbar-item" href="{% url 'sspanel:ssclient' %}">客户端</a>
                <div class="navbar-item has-dropdown is-hoverable is-hidden-mobile">
                    <span class="navbar-item">
                        <a class="button is-info is-inverted" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-user-circle"></i>
                            </span>
                            <span>{{ user.username }}</span>
                        </a>
                    </span>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">
                            <span class="icon">
                                <i class="fa fa-users"></i>
                            </span>
                            <span>用户中心</span>
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url 'sspanel:logout' %}">
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            <span>注销登录</span>
                        </a>
                    </div>
                </div>
                <!-- 手机界面菜单-->
                <div class="is-hidden-tablet">
                    <a class="navbar-item is-active">我的信息</a>
                    <a class="navbar-item" href="{% url 'sspanel:userinfo' %}">账户信息</a>
                    <a class="navbar-item" href="{% url 'sspanel:announcement' %}">查看公告</a>
                    <a class="navbar-item" href="{% url 'sspanel:ticket' %}">联系站长</a>
                    <a class="navbar-item is-active">节点相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:nodeinfo' %}">节点信息</a>
                    <a class="navbar-item" href="{% url 'sspanel:user_traffic_log' %}">流量记录</a>
                    <a class="navbar-item is-active">交易相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:donate' %}">捐赠充值</a>
                    <a class="navbar-item" href="{% url 'sspanel:chargecenter' %}">充值界面</a>
                    <a class="navbar-item" href="{% url 'sspanel:shop' %}">商品界面</a>
                    <a class="navbar-item" href="{% url 'sspanel:purchaselog' %}">购买记录</a>
                    <a class="navbar-item is-active">邀请相关</a>
                    <a class="navbar-item" href="{% url 'sspanel:aff_invite' %}">邀请返利</a>
                    <a class="navbar-item" href="{% url 'sspanel:aff_status' %}">返利记录</a>
                    {% if perms.sspanel %}
                    <a class="navbar-item is-active">管理面板</a>
                    <a class="navbar-item" href="/admin">数据后台</a>
                    <a class="navbar-item" href="{% url 'sspanel:system_status' %}">网站后台</a>
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </nav>
    <section class="hero is-small is-info">
        <div class="hero-body">
            <div class="container has-text-centered">
                <h1 class="title">
                    <a href="/">
                        <strong>{% settings_value "SUBTITLE" %}</strong>
                    </a>
                </h1>
                <h2 class="subtitle">
                    你说会发现什么呢？
                </h2>
            </div>
        </div>
    </section>
    <hr>
    <main class="bd-main">
        <div class="container is-fluid">
            <div class="columns">
                <div class="column is-2 is-hidden-mobile">
                    <div class="box">
                        {% if user.is_authenticated %}
                        <aside class="menu">
                            <p class="menu-label">
                                我的信息：
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a class="" href="{% url 'sspanel:userinfo' %}">账户信息</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:announcement' %}">查看公告</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:ticket' %}">联系站长</a>
                                </li>
                            </ul>
                            <p class="menu-label">
                                节点相关
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:nodeinfo' %}">节点信息</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:user_traffic_log' %}">流量记录</a>
                                </li>
                            </ul>
                            <p class="menu-label">
                                交易相关
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:donate' %}">捐赠付费</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:chargecenter' %}">充值界面</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:shop' %}">商品界面</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:purchaselog' %}">购买记录</a>
                                </li>
                            </ul>
                            <p class="menu-label">
                                邀请相关
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:aff_invite' %}">邀请返利</a>
                                </li>
                                <li>
                                    <a href="{% url 'sspanel:aff_status' %}">返利记录</a>
                                </li>
                            </ul>
                            {% if perms.sspanel %}
                            <p class="menu-label">
                                管理面板
                            </p>
                            <ul class="menu-list">
                                <li>
                                    <a href="/admin">数据后台</a>
                                </li>
                            </ul>
                            <ul class="menu-list">
                                <li>
                                    <a href="{% url 'sspanel:system_status' %}">网站后台</a>
                                </li>
                            </ul>
                            {% endif %} {% else %}
                            <article class="message is-primary">
                                <div class="message-header">
                                    <p>幻想乡：</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    幻想中的:「地方」
                                </div>
                            </article>
                            <article class="message is-info">
                                <div class="message-header">
                                    <p>谜の屋：</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    他不存于:「地表」
                                </div>
                            </article>
                            <article class="message is-success">
                                <div class="message-header">
                                    <p>时之塔：</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    这囚禁着：「思想」
                                </div>
                            </article>
                            <article class="message is-warning">
                                <div class="message-header">
                                    <p>旧の桥</p>
                                    <button class="delete"></button>
                                </div>
                                <div class="message-body">
                                    却连接着：「自由」
                                </div>
                            </article>
                            {% endif %}
                        </aside>
                    </div>
                </div>

                <div class="column is-10">

                    {% block main %} {% endblock main%}

                </div>
            </div>
        </div>
    </main>
    <footer>
        <div class="container">
            <div class="content has-text-centered">
                <p>
                    <p class="copyright">&copy; 2018·
                        <a href="https://github.com/ehco1996">GitHub</a>
                    </p>
                </p>
            </div>
        </div>
    </footer>
</body>
<!--整站消息提醒功能 -->
{% if messages %}
<script>
    {% for message in messages %}
    swal("{{ message.extra_tags }}", '{{ message }}', '{{ message.level_tag }}');
    {% endfor %}
</script>
{% endif %}

</html>

templates/basehead.html
{% load staticfiles %}
<!-- meta -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="{% static 'img/logo/logo.ico' %}" />

<!-- css -->
{% if user.theme %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/bulmaswatch/0.7.2/{{ user.theme }}/bulmaswatch.min.css" rel="stylesheet">
{% if user.theme == "default" %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" rel="stylesheet">
{% endif %}
{% else %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" rel="stylesheet">
{% endif %}

<link rel="stylesheet" href="{% static 'sspanel/css/sspanel.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.3.0/css/flag-icon.min.css">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simplemde/1.11.2/simplemde.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css" rel="stylesheet">

<!-- js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/simplemde/1.11.2/simplemde.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js"></script>
<script src="{% static 'sspanel/js/sspanel.js' %}"></script>